### PR TITLE
Added "insert silence" feature

### PR DESCRIPTION
**Pull request by bitblaster**
Added the capability to insert a specified length of silence starting at some point inside the audio

### CODE REVIEW

**Comment by darealshinji** [comment]
Sorry for the late reply. This looks pretty good. Will take a look at it later.

**Comment by darealshinji** [comment]
This fixes issue #8 and #9 ?

**Comment by bitblaster** [comment]
> This fixes issue #8 and #9 ?

Yes

**Comment by bitblaster** [comment]
@darealshinji: sorry, didn't see your invitation (now expired). 
If you send it again I would be glad to collaborate on this project.

**Comment by darealshinji** [comment]
New invitation sent.

**Comment by bitblaster** [comment]
> New invitation sent.

Accepted, thanks!

**Pull request merged**
